---
title: "Question 7"
author: "Daria Moiseeva"
date: "2023-11-24"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
wholeSet <- read_xlsx("MUE.2022.for.LMU.xlsx")
data <- wholeSet[, c(60, 62, 63, 64, 65, 66, 67, 68)]
data <- na.omit(data) # delete rows with NA
todelete <- c()
for (i in 1:nrow(data)) {
  if (-2 %in% data[i, 1] || -9 %in% data[i, 1]) {
    todelete <- c(todelete, i)
  }
}
data <- data[-todelete, ]
colnames(data) <- c("participation", "challenge1", "challenge2", "challenge3", "challenge4", "challenge5", "challenge6", "challenge7")
library(ggplot2)
library(reshape2)
data
data$participation <- factor(data$participation, 
                             levels = c(-1, 4, 3, 2, 1),
                             labels = c("irregularly", "once a year", "once every half a year", "once a quartal","more often than once a month"))


for(i in 2:8) {
  filtered_data <- data[data[[i]] == TRUE, c(1, i)]
  
  p <- ggplot(filtered_data, aes_string(x = names(filtered_data)[2], fill = "participation")) +
    geom_bar(position = "dodge") +
    labs(title = paste("Challenge", i-1),
         x = "Challenge",
         y = "Count") +
    theme_minimal()
  
  print(p)
}
library(ggplot2)
library(reshape2)
library(dplyr)


data_long <- melt(data, id.vars = "participation", variable.name = "challenge", value.name = "presence")
data_long <- data_long[data_long$presence == TRUE, ]

data_percentage <- data_long %>%
  group_by(challenge, participation) %>%
  summarise(count = n()) %>%
  mutate(total = sum(count),
         percent = count / total * 100)
data_percentage
data_percentage %>%
  filter(challenge!= "challenge7") %>%
  ggplot(aes(fill = participation, y = percent, x = challenge)) +
  geom_bar(position = "stack", stat = "identity") +
   scale_x_discrete(labels = c("Find suitable offers 
                               for participation", 
                              "Get employees to participate", 
                              "Coordination of employees", 
                              "Limited time of employees", 
                              "Cost of the program", 
                              "Lack of support from
                              the management")) +
  labs(title = "Volunteering challenges vs Frequency of volunteering",
       x = "Challenges",
       y = "Percent of companies",
       fill = "Frequency of volunteering:") +
  theme_minimal() +
  theme(axis.text.x = element_text(colour="black",
                                   angle = 45,
                                   hjust = 1,
                                   size = 20),
        title=element_text(size = 20),
        axis.title = element_text(size = 20),
        axis.text.y=element_text(colour="black", size = 20),
        legend.text=element_text(size = 20),
        legend.title=element_text(size = 20)) +
  scale_fill_brewer(palette = "GnBu")

ggsave("7question.jpeg",device = "jpeg",width = 16,height = 9)

``` 